apiVersion: batch/v1
kind: CronJob
metadata:
  name: task
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: task
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  curl -sf https://api.cyber-widget.com/refresh || echo "Job completed at $(date)";
          restartPolicy: OnFailure

