apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-sample
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/aly666/Learn-Devops.git'
    targetRevision: master       # branch master
    path: k8s                    # folder yang berisi deployment.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

