apiVersion: v1
kind: Service
metadata:
  name: cache-db
  namespace: cyberco
spec:
  selector:
    app: cache-db
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  type: ClusterIP

