---
- name: Setup Apache web server and deploy index.html
  hosts: webservers
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600    # 1 hour cache validity (optional)

    - name: Install apache2 package
      apt:
        name: apache2
        state: present

    - name: Ensure apache2 service is enabled and started
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Deploy index.html to document root
      copy:
        dest: /var/www/html/index.html
        content: |
          <!doctype html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Hello Ansible</title>
            </head>
            <body>
              <h1>Hello, Ansible!</h1>
            </body>
          </html>
        owner: root
        group: root
        mode: '0644'

