name: CI/CD Pipeline K3s

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: myflaskapp
  IMAGE_TAG: ${{ github.sha }}
  APP_FOLDER: Learn-Devops/tech-vault-q8

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true  # jika menggunakan submodule

      # Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies dari subfolder
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ env.APP_FOLDER }}/requirements.txt

      # Run unit tests dari subfolder
      - name: Run tests
        run: pytest ${{ env.APP_FOLDER }}/tests/

      # Build Docker image dari subfolder
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ${{ env.APP_FOLDER }}

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        w

